stages:
  - protos
  - build
  - release

variables:
  GRPC_TAG: couchers/grpc #$CI_REGISTRY/couchers/grpc:latest
  PROXY_IMAGE: $CI_REGISTRY_IMAGE/proxy
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  MEDIA_IMAGE: $CI_REGISTRY_IMAGE/media
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  PROXY_TAG: $CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_SLUG
  BACKEND_TAG: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  MEDIA_TAG: $CI_REGISTRY_IMAGE/media:$CI_COMMIT_REF_SLUG
  FRONTEND_TAG: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG

default:
  image: docker
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

protos:
  stage: protos
  image: $GRPC_TAG
  inherit:
    # the grpc container doesn't have docker, no need to login
    default: false
  script:
    - cd app && ./generate_protos.sh
  artifacts:
    paths:
      - ./app

build:proxy:
  stage: build
  script:
    - docker build -t $PROXY_TAG app/proxy/
    - docker push $PROXY_TAG

build:backend:
  stage: build
  script:
    - docker build -t $BACKEND_TAG app/backend/
    - docker push $BACKEND_TAG

build:media:
  stage: build
  script:
    - docker build -t $MEDIA_TAG app/media/
    - docker push $MEDIA_TAG

build:frontend:
  stage: build
  script:
    - docker build -t $FRONTEND_TAG app/frontend/
    - docker push $FRONTEND_TAG

release:proxy:
  stage: release
  script:
    - docker pull $PROXY_TAG
    - docker tag $PROXY_TAG $PROXY_IMAGE:latest
    - docker push $PROXY_IMAGE:latest
  only:
    - develop

release:backend:
  stage: release
  script:
    - docker pull $BACKEND_TAG
    - docker tag $BACKEND_TAG $BACKEND_IMAGE:latest
    - docker push $BACKEND_IMAGE:latest
  only:
    - develop

release:media:
  stage: release
  script:
    - docker pull $MEDIA_TAG
    - docker tag $MEDIA_TAG $MEDIA_IMAGE:latest
    - docker push $MEDIA_IMAGE:latest
  only:
    - develop

release:frontend:
  stage: release
  script:
    - docker pull $FRONTEND_TAG
    - docker tag $FRONTEND_TAG $FRONTEND_IMAGE:latest
    - docker push $FRONTEND_IMAGE:latest
  only:
    - develop
