version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - cd site
      - yarn install
  build:
    commands:
      - yarn generate-all
  post_build:
    commands:
      - echo "Done."