version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - cd site
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn generate-all
  post_build:
    commands:
      - aws s3 sync dist/ s3://couchers.org --acl public-read
      - echo "Done."
