version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            cd app
            pip install grpcio-tools
            PROTOC="python -m grpc_tools.protoc" ./generate_protos.sh
      - run:
          command: |
            cd app/backend
            pip install -r requirements.txt
            pytest src
