version: 2
jobs:
  grpc:
    docker:
      - image: couchers/grpc
    steps:
      - checkout
      - run: cd app && ./generate_protos.sh
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  backend_tests:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            cd app/backend
            pip install -r requirements.txt
            pytest src
      - store_test_results:
          path: app/backend
  media_tests:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            cd app/media
            pip install -r requirements.txt
            MEDIA_SERVER_FROM_ENV=0 pytest .
workflows:
  version: 2
  backend:
    jobs:
      - grpc
      - backend_tests:
          requires:
            - grpc
  media:
    jobs:
      - grpc
      - media_tests:
          requires:
            - grpc
