version: 2
jobs:
  compile_protos:
    docker:
      - image: couchers/grpc
    steps:
      - checkout
      - run: cd app && ./generate_protos.sh
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  build_backend:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            cd app/backend
            docker build -t couchers/backend .
      - run: docker save -o couchers-backend.tar.gz couchers/backend
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  test_backend:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker load -i couchers-backend.tar.gz
      - run: docker run couchers/backend pytest src
  build_media:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            cd app/media
            docker build -t couchers/media .
      - run: docker save -o couchers-media.tar.gz couchers/media
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  test_media:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker load -i couchers-media.tar.gz
      - run: docker run couchers/media pytest src
workflows:
  version: 2
  backend:
    jobs:
      - compile_protos
      - build_backend:
          requires:
            - compile_protos
      - test_backend:
          requires:
            - build_backend
  media:
    jobs:
      - compile_protos
      - build_media:
          requires:
            - compile_protos
      - test_media:
          requires:
            - build_media
