version: 2
jobs:
  build:
    docker:
      - image: couchers/grpc
    steps:
      - checkout
      - run:
          command: cd app && ./generate_protos.sh
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          command: |
            cd app/backend
            pip install -r requirements.txt
            pytest src
      - run:
          command: |
            cd app/media
            pip install -r requirements.txt
            MEDIA_SERVER_FROM_ENV: 0 pytest .
