version: 2
jobs:
  compile_protos:
    docker:
      - image: couchers/grpc
    steps:
      - checkout
      - run: cd app && ./generate_protos.sh
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  build_backend:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            cd app/backend
            docker build -t couchers/backend .
workflows:
  version: 2
  backend:
    jobs:
      - compile_protos
      - build_backend:
          requires:
            - compile_protos
