version: 2
jobs:
  build:
    working_directory: ~/app/backend
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
