version: 2
jobs:
  build:
    docker:
      - image: aapeliv/grpc
    steps:
      - checkout
      - run:
          command: |
            cd app
            ls
            bash generate_protos.sh
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          command: |
            cd app/backend
            pip install -r requirements.txt
            pytest src
