version: 2
jobs:
  build:
    docker:
      - image: couchers/grpc
    steps:
      - checkout
      - run: cd app && ./generate_protos.sh
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            cd app/backend
            pip install -r requirements.txt
            pytest src
      - store_test_results:
          path: app/backend
      - run:
          command: |
            cd app/media
            pip install -r requirements.txt
            MEDIA_SERVER_FROM_ENV: 0 pytest .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
