version: "3"
services:
  proxy:
    build: proxy
    restart: always
    ports:
      - 8888:8888
      - 9901:9901
  backend:
    build: backend
    volumes:
      - "./backend:/app"
    restart: always
    ports:
      - 1751:1751
  frontend:
    build: frontend
    volumes:
      - "./frontend:/app"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - backend
    links:
      - backend
