version: "3"
services:
  proxy:
    build: proxy
    restart: on-failure
    ports:
      - 8888:8888
      - 9901:9901
  backend:
    build: backend
    restart: on-failure
    ports:
      - 1751:1751
      - 1752:1752
  frontend:
    build: frontend
    volumes:
      - "./frontend:/app"
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - backend
    links:
      - backend
