version: "3.8"
services:
  postgres:
    image: postgis/postgis:13-3.0
    restart: on-failure
    env_file: postgres.prod.env
    volumes:
      - "./data/postgres/pgdata/:/var/lib/postgresql/data/"
    ports:
      - 5432:5432
    networks:
      - postgres_backend
  backend:
    image: registry.gitlab.com/couchers/couchers/backend
    restart: on-failure
    env_file: backend.prod.env
    expose:
      - 1751
      - 1752
      - 1753
    depends_on:
      - postgres
    networks:
      - postgres_backend
      - backend_media
      - backend_envoy
  media:
    image: registry.gitlab.com/couchers/couchers/media
    restart: on-failure
    env_file: media.prod.env
    volumes:
      - "./data/media/uploads:/uploads"
    expose:
      - 5000
    depends_on:
      - backend
    networks:
      - backend_media
      - media_nginx
  envoy:
    image: registry.gitlab.com/couchers/couchers/proxy
    restart: on-failure
    expose:
      - 8888
      - 9901
    networks:
      - backend_envoy
      - envoy_nginx
  nginx:
    build: nginx
    #image: registry.gitlab.com/couchers/couchers/nginx
    restart: on-failure
    build: nginx
    env_file: nginx.prod.env
    volumes:
      - "./data/certs/:/certs/"
      - "./data/nginx/logs/:/var/log/nginx/"
    ports:
      #- 80:80 # we don't support HTTP on the APIs, etc
      - 443:443
    networks:
      - media_nginx
      - envoy_nginx
networks:
  postgres_backend:
    driver: bridge
  backend_media:
    driver: bridge
  backend_envoy:
    driver: bridge
  media_nginx:
    driver: bridge
  envoy_nginx:
    driver: bridge
