version: "3"
services:
  proxy:
    build: proxy
    restart: on-failure
    ports:
      - 8888:8888
      - 9901:9901
  backend_tests:
    build: backend
    volumes:
      - "./backend:/app"
    command: bash -c "find src -name '**.py' | ENTR_INOTIFY_WORKAROUND=1 entr -d pytest src"
    restart: on-failure
  backend:
    build: backend
    volumes:
      - "./backend:/app"
    # see https://github.com/eradman/entr#docker-and-windows-subsystem-for-linux
    command: bash -c "find src -name '**.py' | ENTR_INOTIFY_WORKAROUND=1 entr -rd python src/app.py"
    restart: on-failure
    ports:
      - 1751:1751
      - 1752:1752
  frontend:
    build: frontend
    volumes:
      - "./frontend:/app"
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - backend
    links:
      - backend
